import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Pixeldrawer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.canvas}>
          <table className={styles.canvasTable}>
            <tbody>
            </tbody>
          </table>
        </div>
      </main>
    </div>
  )
}

export default Home
