import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const x: number[] = Array.from(Array(1617).keys());
  const y: number[] = Array.from(Array(700).keys());

  return (
    <div>
      <Head>
        <title>Pixeldrawer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.canvas}>
          <div className={styles.canvasPixels}>
            {x.map((number) =>
              <div className={styles.canvasPixel}></div>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
